### ISSUE TITLE
Don't count 'use strict' as literal

### ISSUE THREAD

**Issue by kurtextrem** [lukastaegert/eslint-plugin-tree-shaking#14]
Msg: `[eslint] Cannot determine side-effects of executing Literal as a statement (tree-shaking/no-side-effects-in-initialization)`

Code:
```javascript
(function (window) {
	'use strict'
```

**Comment by lukastaegert** [comment]
Hi @kurtextrem , sorry for not getting back to you earlier. I am little unsure how to treat this. The reason is the following: In the current version of rollup, if you write "use strict" anywhere, than this code (and its surrounding statements) will NOT be tree-shaken.

So the recommendation is not to write "use strict". When you have ES6 modules, "use strict" is implicitly assumed anyway. When rollup (and to my knowledge, webpack as well) package your code into something other than an ES6 module, "use strict" is also added at the top automatically, see the examples here: [rollup REPL](https://rollupjs.org/repl?version=0.49.3)

For that reason, I am somewhat reluctant to remove this. May I ask what your use-case is for writing "use strict" explicitly so that I understand it better?

**Comment by kurtextrem** [comment]
Oh, I did not know that. That's quite nice to know.

Well, thing is I use the same eslint config for all of my projects (and some aren't using webpack/rollup). Thank you for the clarification!

**Comment by lukastaegert** [comment]
Actually it's [in the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code).

> Module code is always strict mode code

I.e. you will only need it when not using ES6 modules, independent of the bundler.

**Comment by kurtextrem** [comment]
Those projects mostly consist of non-modules (so to say 'old' regular JS code) and I was wondering why 'use strict' is highlighted.
